name: build
on:
  push:
  pull_request:
jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        if: startsWith(matrix.platform, 'ubuntu')
        run: sudo apt install tk

      - name: Build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.3'
          spec: ModEnabler.py
          requirements: requirements.txt
          options: --onefile, --noconsole

      - name: Upload ${{ matrix.platform }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: dist/*
